/**
  * PQStudio A group of unknown boys who create happy games
  * PQStudio The first stage 2021-2031
  */


// @generated by protobuf-ts 2.0.15
// @generated from protobuf file "protobuf-ts.proto" (syntax proto3)
// @ts-nocheck
// tslint:disable
import { register,PQMessages } from "../protobuf/index";
import { MessageType } from "../protobuf/index";
/**
 * 角色信息
 *
 * @generated from protobuf message Role
 */
export interface Role {
    /**
     * 角色名
     *
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * 角色等级
     *
     * @generated from protobuf field: string level = 2;
     */
    level: string;
    /**
     * vip等级
     *
     * @generated from protobuf field: repeated int32 vip = 3;
     */
    vip: number[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Role$Type extends MessageType<Role> {
    constructor() {
        super(PQMessages.MRole, "Role", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "level", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "vip", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Role
 */
export const Role = new Role$Type();
register(Role.protoID, Role);
